# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\dell\OneDrive\Masaüstü\pyqt5\3 timer\timer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setStyleSheet("background-color: rgb(133, 148, 145);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ButtonStart_2 = QtWidgets.QPushButton(self.centralwidget)
        self.ButtonStart_2.setGeometry(QtCore.QRect(170, 290, 63, 59))
        self.ButtonStart_2.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.ButtonStart_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonStart_2.setIcon(icon)
        self.ButtonStart_2.setIconSize(QtCore.QSize(50, 50))
        self.ButtonStart_2.setObjectName("ButtonStart_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(50, 30, 299, 251))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_set_time = QtWidgets.QLabel(self.splitter)
        self.label_set_time.setStyleSheet("font: 75 10pt \"Verdana\";\n"
"background-color: rgb(164, 195, 178)\n"
"")
        self.label_set_time.setScaledContents(False)
        self.label_set_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_set_time.setWordWrap(False)
        self.label_set_time.setObjectName("label_set_time")
        self.label_timer = QtWidgets.QLabel(self.splitter)
        self.label_timer.setStyleSheet("background-color: rgb(107, 144, 128);\n"
"font: 75 10pt \"Verdana\";")
        self.label_timer.setAlignment(QtCore.Qt.AlignCenter)
        self.label_timer.setObjectName("label_timer")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.ButtonStart = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonStart.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("play.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonStart.setIcon(icon1)
        self.ButtonStart.setIconSize(QtCore.QSize(50, 50))
        self.ButtonStart.setObjectName("ButtonStart")
        self.horizontalLayout.addWidget(self.ButtonStart)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.ButtonPaus = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonPaus.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonPaus.setIcon(icon2)
        self.ButtonPaus.setIconSize(QtCore.QSize(50, 50))
        self.ButtonPaus.setObjectName("ButtonPaus")
        self.horizontalLayout.addWidget(self.ButtonPaus)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.ButtonReset = QtWidgets.QPushButton(self.layoutWidget)
        self.ButtonReset.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("reset2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ButtonReset.setIcon(icon3)
        self.ButtonReset.setIconSize(QtCore.QSize(50, 50))
        self.ButtonReset.setObjectName("ButtonReset")
        self.horizontalLayout.addWidget(self.ButtonReset)
        self.splitter.raise_()
        self.ButtonStart_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon4)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.ButtonStart_2.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Timer"))
        self.label_set_time.setText(_translate("MainWindow", "Set Time(s)"))
        self.label_timer.setText(_translate("MainWindow", "20:00"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

