# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/melike/Desktop/set_time/time_setter.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setter_window(object):
    def setupUi(self, setter_window):
        setter_window.setObjectName("setter_window")
        setter_window.resize(400, 500)
        setter_window.setMinimumSize(QtCore.QSize(400, 500))
        setter_window.setMaximumSize(QtCore.QSize(400, 500))
        font = QtGui.QFont()
        font.setPointSize(36)
        setter_window.setFont(font)
        setter_window.setStyleSheet("background-color: rgb(231, 202, 255);")
        self.setterwdw_btn_set = QtWidgets.QPushButton(setter_window)
        self.setterwdw_btn_set.setGeometry(QtCore.QRect(120, 220, 161, 91))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.setterwdw_btn_set.setFont(font)
        self.setterwdw_btn_set.setStyleSheet("background-color: rgb(191, 167, 210);\n"
"font: 36pt \"Comic Sans MS\";")
        self.setterwdw_btn_set.setObjectName("setterwdw_btn_set")
        self.setterwdw_spinbox_seconds = QtWidgets.QSpinBox(setter_window)
        self.setterwdw_spinbox_seconds.setGeometry(QtCore.QRect(110, 150, 181, 51))
        self.setterwdw_spinbox_seconds.setStyleSheet("background-color: rgb(180, 221, 246);\n"
"font: 24pt \"Comic Sans MS\";")
        self.setterwdw_spinbox_seconds.setMaximum(120)
        self.setterwdw_spinbox_seconds.setSingleStep(5)
        self.setterwdw_spinbox_seconds.setObjectName("setterwdw_spinbox_seconds")

        self.retranslateUi(setter_window)
        QtCore.QMetaObject.connectSlotsByName(setter_window)

    def retranslateUi(self, setter_window):
        _translate = QtCore.QCoreApplication.translate
        setter_window.setWindowTitle(_translate("setter_window", "Time Setter"))
        self.setterwdw_btn_set.setText(_translate("setter_window", "SET"))
        self.setterwdw_spinbox_seconds.setSuffix(_translate("setter_window", " seconds"))
