# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\karakurt\Documents\GitHub\homework\WEEK-8 PYQT5\05-Nuseybe\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(256, 250)
        Dialog.setMaximumSize(QtCore.QSize(300, 250))
        Dialog.setStyleSheet("background-color: rgb(251, 231, 255);")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(120, 190, 81, 41))
        self.pushButton.setStyleSheet("font: 12pt \"Montserrat\";")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 171, 151))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Montserrat\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        self.pushButton.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Exit"))
        self.label.setText(_translate("Dialog", "This Program has been created by Nuseybe at 24.01.2023"))
