# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\karakurt\Documents\GitHub\homework\WEEK-8 PYQT5\05-Nuseybe\main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 250))
        MainWindow.setMaximumSize(QtCore.QSize(500, 500))
        MainWindow.setStyleSheet("background-color: rgb(251, 231, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.start = QtWidgets.QPushButton(self.centralwidget)
        self.start.setGeometry(QtCore.QRect(160, 200, 81, 81))
        self.start.setStyleSheet("background-color: rgb(212, 255, 172);\n"
"border-radius:40px\n"
"")
        self.start.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\homework\\WEEK-8 PYQT5\\05-Nuseybe\\../timer/pllay.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon)
        self.start.setIconSize(QtCore.QSize(50, 50))
        self.start.setObjectName("start")
        self.pause = QtWidgets.QPushButton(self.centralwidget)
        self.pause.setGeometry(QtCore.QRect(160, 200, 81, 81))
        self.pause.setStyleSheet("background-color: rgb(85, 255, 255);\n"
"border-radius:40px")
        self.pause.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\homework\\WEEK-8 PYQT5\\05-Nuseybe\\pause.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause.setIcon(icon1)
        self.pause.setIconSize(QtCore.QSize(50, 50))
        self.pause.setObjectName("pause")
        self.reset = QtWidgets.QPushButton(self.centralwidget)
        self.reset.setGeometry(QtCore.QRect(280, 200, 81, 81))
        self.reset.setStyleSheet("background-color: rgb(255, 190, 254);\n"
"border-radius:40px")
        self.reset.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\homework\\WEEK-8 PYQT5\\05-Nuseybe\\../timer/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.reset.setIcon(icon2)
        self.reset.setIconSize(QtCore.QSize(50, 50))
        self.reset.setObjectName("reset")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(150, 300, 221, 61))
        self.exit.setStyleSheet("background-color: rgb(85, 85, 255);\n"
"color: rgb(255, 255, 255);\n"
"font: 81 18pt \"Montserrat ExtraBold\";\n"
"border-radius: 21px")
        self.exit.setObjectName("exit")
        self.count = QtWidgets.QLabel(self.centralwidget)
        self.count.setGeometry(QtCore.QRect(100, 120, 301, 71))
        self.count.setStyleSheet("font: 63 22pt \"Montserrat SemiBold\";\n"
"background-color: rgb(251, 255, 224);\n"
"border-radius : 21px")
        self.count.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.count.setAlignment(QtCore.Qt.AlignCenter)
        self.count.setObjectName("count")
        self.timeset = QtWidgets.QPushButton(self.centralwidget)
        self.timeset.setGeometry(QtCore.QRect(100, 30, 301, 71))
        self.timeset.setStyleSheet("font: 87 16pt \"Montserrat Black\";\n"
"background-color: rgb(210, 206, 255);\n"
"border-radius : 21px")
        self.timeset.setObjectName("timeset")
        self.pause.raise_()
        self.start.raise_()
        self.reset.raise_()
        self.exit.raise_()
        self.count.raise_()
        self.timeset.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 500, 26))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\karakurt\\Documents\\GitHub\\homework\\WEEK-8 PYQT5\\05-Nuseybe\\../timer/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionExit.setObjectName("actionExit")
        self.menuMenu.addAction(self.actionAbout)
        self.menuMenu.addAction(self.actionExit)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        self.exit.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.count.setText(_translate("MainWindow", "Timer"))
        self.timeset.setText(_translate("MainWindow", "Set Timer(s)"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "About "))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
